export const SET_SEARCH = "SET_SEARCH";
export const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";
export const SET_SEARCH_MENU_FILTER = "SET_SEARCH_MENU_FILTER";
export const SET_SEARCH_INPUT_FILTER = "SET_SEARCH_INPUT_FILTER";
export const FILTER_SEARCH = "FILTER_SEARCH";